Name: aws-sdk-cpp
Version: 1.9.145
Release: 1%{?dist}
Summary: AWS C++ SDK
License: MIT
URL: https://github.com/aws/aws-sdk-cpp

# curl -L https://github.com/aws/aws-sdk-cpp/archive/1.5.25.tar.gz -o aws-sdk-cpp-1.5.25.tar.gz
Source: %{name}-%{version}.tar.gz

BuildRequires: gcc-c++ cmake3 zlib zlib-devel openssl openssl-devel curl curl-devel

%description
Amazon AWS SDK for C++

#TODO further split this out into core- and other AWS tools

# no debug packages
%global debug_package %{nil}

%package dynamodb-devel
Summary: headers for AWS C++ SDK for DynamoDB
Group: Development/Libraries
%description dynamodb-devel
%{summary}.

%package dynamodb-libs
Summary: AWS C++ SDK runtime libraries for DynamoDB
Group: System Environment/Libraries
%description dynamodb-libs
%{summary}.

%prep
%setup -c -n %{name}-%{version}.tar.gz 

%build
cd %{name}-%{version}
mkdir build
cd build
cmake3 .. -DBUILD_ONLY="dynamodb" -DBUILD_SHARED_LIBS=Off
make

%install
cd %{name}-%{version}
cd build
rm -rf $RPM_BUILD_ROOT
echo $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/usr/{include,lib64}
mv $RPM_BUILD_ROOT/usr/local/include/aws $RPM_BUILD_ROOT/usr/include/aws
mv $RPM_BUILD_ROOT/usr/local/include/* $RPM_BUILD_ROOT/usr/include/
mv $RPM_BUILD_ROOT/usr/local/lib64/cmake $RPM_BUILD_ROOT/usr/lib64/cmake
mv $RPM_BUILD_ROOT/usr/local/lib64/*.a $RPM_BUILD_ROOT/usr/lib64/
mv $RPM_BUILD_ROOT/usr/local/lib64/* $RPM_BUILD_ROOT/usr/lib64/
cd ..

%clean
rm -rf $RPM_BUILD_ROOT

%post
/sbin/ldconfig

%postun
/sbin/ldconfig

%files dynamodb-devel
%defattr(-,root,root,-)
%{_includedir}/aws/core/AmazonSerializableWebServiceRequest.h
%{_includedir}/aws/core/AmazonStreamingWebServiceRequest.h
%{_includedir}/aws/core/AmazonWebServiceRequest.h
%{_includedir}/aws/core/AmazonWebServiceResult.h
%{_includedir}/aws/core/Aws.h
%{_includedir}/aws/core/Core_EXPORTS.h
%{_includedir}/aws/core/Globals.h
%{_includedir}/aws/core/NoResult.h
%{_includedir}/aws/core/Region.h
%{_includedir}/aws/core/SDKConfig.h
%{_includedir}/aws/core/Version.h
%{_includedir}/aws/core/VersionConfig.h
%{_includedir}/aws/core/auth/AWSAuthSigner.h
%{_includedir}/aws/core/auth/AWSAuthSignerProvider.h
%{_includedir}/aws/core/auth/AWSCredentialsProvider.h
%{_includedir}/aws/core/auth/AWSCredentialsProviderChain.h
%{_includedir}/aws/core/client/AWSClient.h
%{_includedir}/aws/core/client/AWSError.h
%{_includedir}/aws/core/client/AWSErrorMarshaller.h
%{_includedir}/aws/core/client/AsyncCallerContext.h
%{_includedir}/aws/core/client/ClientConfiguration.h
%{_includedir}/aws/core/client/CoreErrors.h
%{_includedir}/aws/core/client/DefaultRetryStrategy.h
%{_includedir}/aws/core/client/RetryStrategy.h
%{_includedir}/aws/core/config/AWSProfileConfigLoader.h
%{_includedir}/aws/core/external/cjson/cJSON.h
%{_includedir}/aws/core/external/tinyxml2/tinyxml2.h
%{_includedir}/aws/core/http/HttpClient.h
%{_includedir}/aws/core/http/HttpClientFactory.h
%{_includedir}/aws/core/http/HttpRequest.h
%{_includedir}/aws/core/http/HttpResponse.h
%{_includedir}/aws/core/http/HttpTypes.h
%{_includedir}/aws/core/http/Scheme.h
%{_includedir}/aws/core/http/URI.h
%{_includedir}/aws/core/http/curl/CurlHandleContainer.h
%{_includedir}/aws/core/http/curl/CurlHttpClient.h
%{_includedir}/aws/core/http/standard/StandardHttpRequest.h
%{_includedir}/aws/core/http/standard/StandardHttpResponse.h
%{_includedir}/aws/core/internal/AWSHttpResourceClient.h
%{_includedir}/aws/core/platform/Android.h
%{_includedir}/aws/core/platform/Environment.h
%{_includedir}/aws/core/platform/FileSystem.h
%{_includedir}/aws/core/platform/OSVersionInfo.h
%{_includedir}/aws/core/platform/Platform.h
%{_includedir}/aws/core/platform/Security.h
%{_includedir}/aws/core/platform/Time.h
%{_includedir}/aws/core/utils/Array.h
%{_includedir}/aws/core/utils/DNS.h
%{_includedir}/aws/core/utils/DateTime.h
%{_includedir}/aws/core/utils/EnumParseOverflowContainer.h
%{_includedir}/aws/core/utils/FileSystemUtils.h
%{_includedir}/aws/core/utils/GetTheLights.h
%{_includedir}/aws/core/utils/HashingUtils.h
%{_includedir}/aws/core/utils/Outcome.h
%{_includedir}/aws/core/utils/ResourceManager.h
%{_includedir}/aws/core/utils/StringUtils.h
%{_includedir}/aws/core/utils/UUID.h
%{_includedir}/aws/core/utils/UnreferencedParam.h
%{_includedir}/aws/core/utils/base64/Base64.h
%{_includedir}/aws/core/utils/crypto/Cipher.h
%{_includedir}/aws/core/utils/crypto/ContentCryptoMaterial.h
%{_includedir}/aws/core/utils/crypto/ContentCryptoScheme.h
%{_includedir}/aws/core/utils/crypto/CryptoBuf.h
%{_includedir}/aws/core/utils/crypto/CryptoStream.h
%{_includedir}/aws/core/utils/crypto/EncryptionMaterials.h
%{_includedir}/aws/core/utils/crypto/Factories.h
%{_includedir}/aws/core/utils/crypto/HMAC.h
%{_includedir}/aws/core/utils/crypto/Hash.h
%{_includedir}/aws/core/utils/crypto/HashResult.h
%{_includedir}/aws/core/utils/crypto/KeyWrapAlgorithm.h
%{_includedir}/aws/core/utils/crypto/MD5.h
%{_includedir}/aws/core/utils/crypto/SecureRandom.h
%{_includedir}/aws/core/utils/crypto/Sha256.h
%{_includedir}/aws/core/utils/crypto/Sha256HMAC.h
%{_includedir}/aws/core/utils/crypto/openssl/CryptoImpl.h
%{_includedir}/aws/core/utils/json/JsonSerializer.h
%{_includedir}/aws/core/utils/logging/AWSLogging.h
%{_includedir}/aws/core/utils/logging/ConsoleLogSystem.h
%{_includedir}/aws/core/utils/logging/DefaultLogSystem.h
%{_includedir}/aws/core/utils/logging/FormattedLogSystem.h
%{_includedir}/aws/core/utils/logging/LogLevel.h
%{_includedir}/aws/core/utils/logging/LogMacros.h
%{_includedir}/aws/core/utils/logging/LogSystemInterface.h
%{_includedir}/aws/core/utils/logging/NullLogSystem.h
%{_includedir}/aws/core/utils/memory/AWSMemory.h
%{_includedir}/aws/core/utils/memory/MemorySystemInterface.h
%{_includedir}/aws/core/utils/memory/stl/AWSAllocator.h
%{_includedir}/aws/core/utils/memory/stl/AWSDeque.h
%{_includedir}/aws/core/utils/memory/stl/AWSList.h
%{_includedir}/aws/core/utils/memory/stl/AWSMap.h
%{_includedir}/aws/core/utils/memory/stl/AWSMultiMap.h
%{_includedir}/aws/core/utils/memory/stl/AWSQueue.h
%{_includedir}/aws/core/utils/memory/stl/AWSSet.h
%{_includedir}/aws/core/utils/memory/stl/AWSStack.h
%{_includedir}/aws/core/utils/memory/stl/AWSStreamFwd.h
%{_includedir}/aws/core/utils/memory/stl/AWSString.h
%{_includedir}/aws/core/utils/memory/stl/AWSStringStream.h
%{_includedir}/aws/core/utils/memory/stl/AWSVector.h
%{_includedir}/aws/core/utils/memory/stl/SimpleStringStream.h
%{_includedir}/aws/core/utils/ratelimiter/DefaultRateLimiter.h
%{_includedir}/aws/core/utils/ratelimiter/RateLimiterInterface.h
%{_includedir}/aws/core/utils/stream/PreallocatedStreamBuf.h
%{_includedir}/aws/core/utils/stream/ResponseStream.h
%{_includedir}/aws/core/utils/stream/SimpleStreamBuf.h
%{_includedir}/aws/core/utils/threading/Executor.h
%{_includedir}/aws/core/utils/threading/ReaderWriterLock.h
%{_includedir}/aws/core/utils/threading/Semaphore.h
%{_includedir}/aws/core/utils/threading/ThreadTask.h
%{_includedir}/aws/core/utils/xml/XmlSerializer.h
%{_includedir}/aws/dynamodb/DynamoDBClient.h
%{_includedir}/aws/dynamodb/DynamoDBEndpoint.h
%{_includedir}/aws/dynamodb/DynamoDBErrorMarshaller.h
%{_includedir}/aws/dynamodb/DynamoDBErrors.h
%{_includedir}/aws/dynamodb/DynamoDBRequest.h
%{_includedir}/aws/dynamodb/DynamoDB_EXPORTS.h
%{_includedir}/aws/dynamodb/model/AttributeAction.h
%{_includedir}/aws/dynamodb/model/AttributeDefinition.h
%{_includedir}/aws/dynamodb/model/AttributeValue.h
%{_includedir}/aws/dynamodb/model/AttributeValueUpdate.h
%{_includedir}/aws/dynamodb/model/AttributeValueValue.h
%{_includedir}/aws/dynamodb/model/AutoScalingPolicyDescription.h
%{_includedir}/aws/dynamodb/model/AutoScalingPolicyUpdate.h
%{_includedir}/aws/dynamodb/model/AutoScalingSettingsDescription.h
%{_includedir}/aws/dynamodb/model/AutoScalingSettingsUpdate.h
%{_includedir}/aws/dynamodb/model/AutoScalingTargetTrackingScalingPolicyConfigurationDescription.h
%{_includedir}/aws/dynamodb/model/AutoScalingTargetTrackingScalingPolicyConfigurationUpdate.h
%{_includedir}/aws/dynamodb/model/BackupDescription.h
%{_includedir}/aws/dynamodb/model/BackupDetails.h
%{_includedir}/aws/dynamodb/model/BackupStatus.h
%{_includedir}/aws/dynamodb/model/BackupSummary.h
%{_includedir}/aws/dynamodb/model/BackupType.h
%{_includedir}/aws/dynamodb/model/BackupTypeFilter.h
%{_includedir}/aws/dynamodb/model/BatchGetItemRequest.h
%{_includedir}/aws/dynamodb/model/BatchGetItemResult.h
%{_includedir}/aws/dynamodb/model/BatchWriteItemRequest.h
%{_includedir}/aws/dynamodb/model/BatchWriteItemResult.h
%{_includedir}/aws/dynamodb/model/Capacity.h
%{_includedir}/aws/dynamodb/model/ComparisonOperator.h
%{_includedir}/aws/dynamodb/model/Condition.h
%{_includedir}/aws/dynamodb/model/ConditionalOperator.h
%{_includedir}/aws/dynamodb/model/ConsumedCapacity.h
%{_includedir}/aws/dynamodb/model/ContinuousBackupsDescription.h
%{_includedir}/aws/dynamodb/model/ContinuousBackupsStatus.h
%{_includedir}/aws/dynamodb/model/CreateBackupRequest.h
%{_includedir}/aws/dynamodb/model/CreateBackupResult.h
%{_includedir}/aws/dynamodb/model/CreateGlobalSecondaryIndexAction.h
%{_includedir}/aws/dynamodb/model/CreateGlobalTableRequest.h
%{_includedir}/aws/dynamodb/model/CreateGlobalTableResult.h
%{_includedir}/aws/dynamodb/model/CreateReplicaAction.h
%{_includedir}/aws/dynamodb/model/CreateTableRequest.h
%{_includedir}/aws/dynamodb/model/CreateTableResult.h
%{_includedir}/aws/dynamodb/model/DeleteBackupRequest.h
%{_includedir}/aws/dynamodb/model/DeleteBackupResult.h
%{_includedir}/aws/dynamodb/model/DeleteGlobalSecondaryIndexAction.h
%{_includedir}/aws/dynamodb/model/DeleteItemRequest.h
%{_includedir}/aws/dynamodb/model/DeleteItemResult.h
%{_includedir}/aws/dynamodb/model/DeleteReplicaAction.h
%{_includedir}/aws/dynamodb/model/DeleteRequest.h
%{_includedir}/aws/dynamodb/model/DeleteTableRequest.h
%{_includedir}/aws/dynamodb/model/DeleteTableResult.h
%{_includedir}/aws/dynamodb/model/DescribeBackupRequest.h
%{_includedir}/aws/dynamodb/model/DescribeBackupResult.h
%{_includedir}/aws/dynamodb/model/DescribeContinuousBackupsRequest.h
%{_includedir}/aws/dynamodb/model/DescribeContinuousBackupsResult.h
%{_includedir}/aws/dynamodb/model/DescribeGlobalTableRequest.h
%{_includedir}/aws/dynamodb/model/DescribeGlobalTableResult.h
%{_includedir}/aws/dynamodb/model/DescribeGlobalTableSettingsRequest.h
%{_includedir}/aws/dynamodb/model/DescribeGlobalTableSettingsResult.h
%{_includedir}/aws/dynamodb/model/DescribeLimitsRequest.h
%{_includedir}/aws/dynamodb/model/DescribeLimitsResult.h
%{_includedir}/aws/dynamodb/model/DescribeTableRequest.h
%{_includedir}/aws/dynamodb/model/DescribeTableResult.h
%{_includedir}/aws/dynamodb/model/DescribeTimeToLiveRequest.h
%{_includedir}/aws/dynamodb/model/DescribeTimeToLiveResult.h
%{_includedir}/aws/dynamodb/model/ExpectedAttributeValue.h
%{_includedir}/aws/dynamodb/model/GetItemRequest.h
%{_includedir}/aws/dynamodb/model/GetItemResult.h
%{_includedir}/aws/dynamodb/model/GlobalSecondaryIndex.h
%{_includedir}/aws/dynamodb/model/GlobalSecondaryIndexDescription.h
%{_includedir}/aws/dynamodb/model/GlobalSecondaryIndexInfo.h
%{_includedir}/aws/dynamodb/model/GlobalSecondaryIndexUpdate.h
%{_includedir}/aws/dynamodb/model/GlobalTable.h
%{_includedir}/aws/dynamodb/model/GlobalTableDescription.h
%{_includedir}/aws/dynamodb/model/GlobalTableGlobalSecondaryIndexSettingsUpdate.h
%{_includedir}/aws/dynamodb/model/GlobalTableStatus.h
%{_includedir}/aws/dynamodb/model/IndexStatus.h
%{_includedir}/aws/dynamodb/model/ItemCollectionMetrics.h
%{_includedir}/aws/dynamodb/model/KeySchemaElement.h
%{_includedir}/aws/dynamodb/model/KeyType.h
%{_includedir}/aws/dynamodb/model/KeysAndAttributes.h
%{_includedir}/aws/dynamodb/model/ListBackupsRequest.h
%{_includedir}/aws/dynamodb/model/ListBackupsResult.h
%{_includedir}/aws/dynamodb/model/ListGlobalTablesRequest.h
%{_includedir}/aws/dynamodb/model/ListGlobalTablesResult.h
%{_includedir}/aws/dynamodb/model/ListTablesRequest.h
%{_includedir}/aws/dynamodb/model/ListTablesResult.h
%{_includedir}/aws/dynamodb/model/ListTagsOfResourceRequest.h
%{_includedir}/aws/dynamodb/model/ListTagsOfResourceResult.h
%{_includedir}/aws/dynamodb/model/LocalSecondaryIndex.h
%{_includedir}/aws/dynamodb/model/LocalSecondaryIndexDescription.h
%{_includedir}/aws/dynamodb/model/LocalSecondaryIndexInfo.h
%{_includedir}/aws/dynamodb/model/PointInTimeRecoveryDescription.h
%{_includedir}/aws/dynamodb/model/PointInTimeRecoverySpecification.h
%{_includedir}/aws/dynamodb/model/PointInTimeRecoveryStatus.h
%{_includedir}/aws/dynamodb/model/Projection.h
%{_includedir}/aws/dynamodb/model/ProjectionType.h
%{_includedir}/aws/dynamodb/model/ProvisionedThroughput.h
%{_includedir}/aws/dynamodb/model/ProvisionedThroughputDescription.h
%{_includedir}/aws/dynamodb/model/PutItemRequest.h
%{_includedir}/aws/dynamodb/model/PutItemResult.h
%{_includedir}/aws/dynamodb/model/PutRequest.h
%{_includedir}/aws/dynamodb/model/QueryRequest.h
%{_includedir}/aws/dynamodb/model/QueryResult.h
%{_includedir}/aws/dynamodb/model/Replica.h
%{_includedir}/aws/dynamodb/model/ReplicaDescription.h
%{_includedir}/aws/dynamodb/model/ReplicaGlobalSecondaryIndexSettingsDescription.h
%{_includedir}/aws/dynamodb/model/ReplicaGlobalSecondaryIndexSettingsUpdate.h
%{_includedir}/aws/dynamodb/model/ReplicaSettingsDescription.h
%{_includedir}/aws/dynamodb/model/ReplicaSettingsUpdate.h
%{_includedir}/aws/dynamodb/model/ReplicaStatus.h
%{_includedir}/aws/dynamodb/model/ReplicaUpdate.h
%{_includedir}/aws/dynamodb/model/RestoreSummary.h
%{_includedir}/aws/dynamodb/model/RestoreTableFromBackupRequest.h
%{_includedir}/aws/dynamodb/model/RestoreTableFromBackupResult.h
%{_includedir}/aws/dynamodb/model/RestoreTableToPointInTimeRequest.h
%{_includedir}/aws/dynamodb/model/RestoreTableToPointInTimeResult.h
%{_includedir}/aws/dynamodb/model/ReturnConsumedCapacity.h
%{_includedir}/aws/dynamodb/model/ReturnItemCollectionMetrics.h
%{_includedir}/aws/dynamodb/model/ReturnValue.h
%{_includedir}/aws/dynamodb/model/SSEDescription.h
%{_includedir}/aws/dynamodb/model/SSESpecification.h
%{_includedir}/aws/dynamodb/model/SSEStatus.h
%{_includedir}/aws/dynamodb/model/SSEType.h
%{_includedir}/aws/dynamodb/model/ScalarAttributeType.h
%{_includedir}/aws/dynamodb/model/ScanRequest.h
%{_includedir}/aws/dynamodb/model/ScanResult.h
%{_includedir}/aws/dynamodb/model/Select.h
%{_includedir}/aws/dynamodb/model/SourceTableDetails.h
%{_includedir}/aws/dynamodb/model/SourceTableFeatureDetails.h
%{_includedir}/aws/dynamodb/model/StreamSpecification.h
%{_includedir}/aws/dynamodb/model/StreamViewType.h
%{_includedir}/aws/dynamodb/model/TableDescription.h
%{_includedir}/aws/dynamodb/model/TableStatus.h
%{_includedir}/aws/dynamodb/model/Tag.h
%{_includedir}/aws/dynamodb/model/TagResourceRequest.h
%{_includedir}/aws/dynamodb/model/TimeToLiveDescription.h
%{_includedir}/aws/dynamodb/model/TimeToLiveSpecification.h
%{_includedir}/aws/dynamodb/model/TimeToLiveStatus.h
%{_includedir}/aws/dynamodb/model/UntagResourceRequest.h
%{_includedir}/aws/dynamodb/model/UpdateContinuousBackupsRequest.h
%{_includedir}/aws/dynamodb/model/UpdateContinuousBackupsResult.h
%{_includedir}/aws/dynamodb/model/UpdateGlobalSecondaryIndexAction.h
%{_includedir}/aws/dynamodb/model/UpdateGlobalTableRequest.h
%{_includedir}/aws/dynamodb/model/UpdateGlobalTableResult.h
%{_includedir}/aws/dynamodb/model/UpdateGlobalTableSettingsRequest.h
%{_includedir}/aws/dynamodb/model/UpdateGlobalTableSettingsResult.h
%{_includedir}/aws/dynamodb/model/UpdateItemRequest.h
%{_includedir}/aws/dynamodb/model/UpdateItemResult.h
%{_includedir}/aws/dynamodb/model/UpdateTableRequest.h
%{_includedir}/aws/dynamodb/model/UpdateTableResult.h
%{_includedir}/aws/dynamodb/model/UpdateTimeToLiveRequest.h
%{_includedir}/aws/dynamodb/model/UpdateTimeToLiveResult.h
%{_includedir}/aws/dynamodb/model/WriteRequest.h
%{_includedir}/aws/external/gtest.h
%{_includedir}/aws/testing/MemoryTesting.h
%{_includedir}/aws/testing/ProxyConfig.h
%{_includedir}/aws/testing/TestingEnvironment.h
%{_includedir}/aws/testing/Testing_EXPORTS.h
%{_includedir}/aws/testing/mocks/aws/auth/MockAWSHttpResourceClient.h
%{_includedir}/aws/testing/mocks/http/MockHttpClient.h
%{_includedir}/aws/testing/platform/PlatformTesting.h
%{_includedir}/aws/auth/auth.h
%{_includedir}/aws/auth/aws_imds_client.h
%{_includedir}/aws/auth/credentials.h
%{_includedir}/aws/auth/exports.h
%{_includedir}/aws/auth/signable.h
%{_includedir}/aws/auth/signing.h
%{_includedir}/aws/auth/signing_config.h
%{_includedir}/aws/auth/signing_result.h
%{_includedir}/aws/cal/cal.h
%{_includedir}/aws/cal/ecc.h
%{_includedir}/aws/cal/exports.h
%{_includedir}/aws/cal/hash.h
%{_includedir}/aws/cal/hmac.h
%{_includedir}/aws/checksums/crc.h
%{_includedir}/aws/checksums/exports.h
%{_includedir}/aws/common/allocator.h
%{_includedir}/aws/common/array_list.h
%{_includedir}/aws/common/array_list.inl
%{_includedir}/aws/common/assert.h
%{_includedir}/aws/common/atomics.h
%{_includedir}/aws/common/atomics.inl
%{_includedir}/aws/common/atomics_fallback.inl
%{_includedir}/aws/common/atomics_gnu.inl
%{_includedir}/aws/common/atomics_gnu_old.inl
%{_includedir}/aws/common/atomics_msvc.inl
%{_includedir}/aws/common/bus.h
%{_includedir}/aws/common/byte_buf.h
%{_includedir}/aws/common/byte_order.h
%{_includedir}/aws/common/byte_order.inl
%{_includedir}/aws/common/cache.h
%{_includedir}/aws/common/clock.h
%{_includedir}/aws/common/clock.inl
%{_includedir}/aws/common/command_line_parser.h
%{_includedir}/aws/common/common.h
%{_includedir}/aws/common/condition_variable.h
%{_includedir}/aws/common/config.h
%{_includedir}/aws/common/cpuid.h
%{_includedir}/aws/common/date_time.h
%{_includedir}/aws/common/device_random.h
%{_includedir}/aws/common/encoding.h
%{_includedir}/aws/common/encoding.inl
%{_includedir}/aws/common/environment.h
%{_includedir}/aws/common/error.h
%{_includedir}/aws/common/error.inl
%{_includedir}/aws/common/exports.h
%{_includedir}/aws/common/fifo_cache.h
%{_includedir}/aws/common/file.h
%{_includedir}/aws/common/hash_table.h
%{_includedir}/aws/common/lifo_cache.h
%{_includedir}/aws/common/linked_hash_table.h
%{_includedir}/aws/common/linked_list.h
%{_includedir}/aws/common/linked_list.inl
%{_includedir}/aws/common/log_channel.h
%{_includedir}/aws/common/log_formatter.h
%{_includedir}/aws/common/log_writer.h
%{_includedir}/aws/common/logging.h
%{_includedir}/aws/common/lru_cache.h
%{_includedir}/aws/common/macros.h
%{_includedir}/aws/common/math.cbmc.inl
%{_includedir}/aws/common/math.fallback.inl
%{_includedir}/aws/common/math.gcc_arm64_asm.inl
%{_includedir}/aws/common/math.gcc_builtin.inl
%{_includedir}/aws/common/math.gcc_overflow.inl
%{_includedir}/aws/common/math.gcc_x64_asm.inl
%{_includedir}/aws/common/math.h
%{_includedir}/aws/common/math.inl
%{_includedir}/aws/common/math.msvc.inl
%{_includedir}/aws/common/mutex.h
%{_includedir}/aws/common/package.h
%{_includedir}/aws/common/platform.h
%{_includedir}/aws/common/posix/common.inl
%{_includedir}/aws/common/predicates.h
%{_includedir}/aws/common/priority_queue.h
%{_includedir}/aws/common/process.h
%{_includedir}/aws/common/promise.h
%{_includedir}/aws/common/ref_count.h
%{_includedir}/aws/common/resource_name.h
%{_includedir}/aws/common/ring_buffer.h
%{_includedir}/aws/common/ring_buffer.inl
%{_includedir}/aws/common/rw_lock.h
%{_includedir}/aws/common/statistics.h
%{_includedir}/aws/common/stdbool.h
%{_includedir}/aws/common/stdint.h
%{_includedir}/aws/common/string.h
%{_includedir}/aws/common/string.inl
%{_includedir}/aws/common/system_info.h
%{_includedir}/aws/common/task_scheduler.h
%{_includedir}/aws/common/thread.h
%{_includedir}/aws/common/thread_scheduler.h
%{_includedir}/aws/common/time.h
%{_includedir}/aws/common/uuid.h
%{_includedir}/aws/common/xml_parser.h
%{_includedir}/aws/common/zero.h
%{_includedir}/aws/common/zero.inl
%{_includedir}/aws/compression/compression.h
%{_includedir}/aws/compression/exports.h
%{_includedir}/aws/compression/huffman.h
%{_includedir}/aws/core/auth/AWSCredentials.h
%{_includedir}/aws/core/auth/SSOCredentialsProvider.h
%{_includedir}/aws/core/auth/STSCredentialsProvider.h
%{_includedir}/aws/core/client/SpecifiedRetryableErrorsRetryStrategy.h
%{_includedir}/aws/core/monitoring/CoreMetrics.h
%{_includedir}/aws/core/monitoring/DefaultMonitoring.h
%{_includedir}/aws/core/monitoring/HttpClientMetrics.h
%{_includedir}/aws/core/monitoring/MonitoringFactory.h
%{_includedir}/aws/core/monitoring/MonitoringInterface.h
%{_includedir}/aws/core/monitoring/MonitoringManager.h
%{_includedir}/aws/core/net/Net.h
%{_includedir}/aws/core/net/SimpleUDP.h
%{_includedir}/aws/core/utils/ARN.h
%{_includedir}/aws/core/utils/Cache.h
%{_includedir}/aws/core/utils/ConcurrentCache.h
%{_includedir}/aws/core/utils/Document.h
%{_includedir}/aws/core/utils/crypto/Sha1.h
%{_includedir}/aws/core/utils/event/EventDecoderStream.h
%{_includedir}/aws/core/utils/event/EventEncoderStream.h
%{_includedir}/aws/core/utils/event/EventHeader.h
%{_includedir}/aws/core/utils/event/EventMessage.h
%{_includedir}/aws/core/utils/event/EventStream.h
%{_includedir}/aws/core/utils/event/EventStreamBuf.h
%{_includedir}/aws/core/utils/event/EventStreamDecoder.h
%{_includedir}/aws/core/utils/event/EventStreamEncoder.h
%{_includedir}/aws/core/utils/event/EventStreamErrors.h
%{_includedir}/aws/core/utils/event/EventStreamHandler.h
%{_includedir}/aws/core/utils/logging/CRTLogSystem.h
%{_includedir}/aws/core/utils/logging/CRTLogging.h
%{_includedir}/aws/core/utils/stream/ConcurrentStreamBuf.h
%{_includedir}/aws/crt/Api.h
%{_includedir}/aws/crt/Config.h
%{_includedir}/aws/crt/DateTime.h
%{_includedir}/aws/crt/Exports.h
%{_includedir}/aws/crt/ImdsClient.h
%{_includedir}/aws/crt/JsonObject.h
%{_includedir}/aws/crt/Optional.h
%{_includedir}/aws/crt/StlAllocator.h
%{_includedir}/aws/crt/StringUtils.h
%{_includedir}/aws/crt/StringView.h
%{_includedir}/aws/crt/Types.h
%{_includedir}/aws/crt/UUID.h
%{_includedir}/aws/crt/auth/Credentials.h
%{_includedir}/aws/crt/auth/Signing.h
%{_includedir}/aws/crt/auth/Sigv4Signing.h
%{_includedir}/aws/crt/crypto/HMAC.h
%{_includedir}/aws/crt/crypto/Hash.h
%{_includedir}/aws/crt/http/HttpConnection.h
%{_includedir}/aws/crt/http/HttpConnectionManager.h
%{_includedir}/aws/crt/http/HttpProxyStrategy.h
%{_includedir}/aws/crt/http/HttpRequestResponse.h
%{_includedir}/aws/crt/io/Bootstrap.h
%{_includedir}/aws/crt/io/ChannelHandler.h
%{_includedir}/aws/crt/io/EventLoopGroup.h
%{_includedir}/aws/crt/io/HostResolver.h
%{_includedir}/aws/crt/io/SocketOptions.h
%{_includedir}/aws/crt/io/Stream.h
%{_includedir}/aws/crt/io/TlsOptions.h
%{_includedir}/aws/crt/io/Uri.h
%{_includedir}/aws/crt/mqtt/MqttClient.h
%{_includedir}/aws/dynamodb/model/ArchivalSummary.h
%{_includedir}/aws/dynamodb/model/BatchExecuteStatementRequest.h
%{_includedir}/aws/dynamodb/model/BatchExecuteStatementResult.h
%{_includedir}/aws/dynamodb/model/BatchStatementError.h
%{_includedir}/aws/dynamodb/model/BatchStatementErrorCodeEnum.h
%{_includedir}/aws/dynamodb/model/BatchStatementRequest.h
%{_includedir}/aws/dynamodb/model/BatchStatementResponse.h
%{_includedir}/aws/dynamodb/model/BillingMode.h
%{_includedir}/aws/dynamodb/model/BillingModeSummary.h
%{_includedir}/aws/dynamodb/model/CancellationReason.h
%{_includedir}/aws/dynamodb/model/ConditionCheck.h
%{_includedir}/aws/dynamodb/model/ContributorInsightsAction.h
%{_includedir}/aws/dynamodb/model/ContributorInsightsStatus.h
%{_includedir}/aws/dynamodb/model/ContributorInsightsSummary.h
%{_includedir}/aws/dynamodb/model/CreateReplicationGroupMemberAction.h
%{_includedir}/aws/dynamodb/model/Delete.h
%{_includedir}/aws/dynamodb/model/DeleteReplicationGroupMemberAction.h
%{_includedir}/aws/dynamodb/model/DescribeContributorInsightsRequest.h
%{_includedir}/aws/dynamodb/model/DescribeContributorInsightsResult.h
%{_includedir}/aws/dynamodb/model/DescribeEndpointsRequest.h
%{_includedir}/aws/dynamodb/model/DescribeEndpointsResult.h
%{_includedir}/aws/dynamodb/model/DescribeExportRequest.h
%{_includedir}/aws/dynamodb/model/DescribeExportResult.h
%{_includedir}/aws/dynamodb/model/DescribeKinesisStreamingDestinationRequest.h
%{_includedir}/aws/dynamodb/model/DescribeKinesisStreamingDestinationResult.h
%{_includedir}/aws/dynamodb/model/DescribeTableReplicaAutoScalingRequest.h
%{_includedir}/aws/dynamodb/model/DescribeTableReplicaAutoScalingResult.h
%{_includedir}/aws/dynamodb/model/DestinationStatus.h
%{_includedir}/aws/dynamodb/model/DisableKinesisStreamingDestinationRequest.h
%{_includedir}/aws/dynamodb/model/DisableKinesisStreamingDestinationResult.h
%{_includedir}/aws/dynamodb/model/EnableKinesisStreamingDestinationRequest.h
%{_includedir}/aws/dynamodb/model/EnableKinesisStreamingDestinationResult.h
%{_includedir}/aws/dynamodb/model/Endpoint.h
%{_includedir}/aws/dynamodb/model/ExecuteStatementRequest.h
%{_includedir}/aws/dynamodb/model/ExecuteStatementResult.h
%{_includedir}/aws/dynamodb/model/ExecuteTransactionRequest.h
%{_includedir}/aws/dynamodb/model/ExecuteTransactionResult.h
%{_includedir}/aws/dynamodb/model/ExportDescription.h
%{_includedir}/aws/dynamodb/model/ExportFormat.h
%{_includedir}/aws/dynamodb/model/ExportStatus.h
%{_includedir}/aws/dynamodb/model/ExportSummary.h
%{_includedir}/aws/dynamodb/model/ExportTableToPointInTimeRequest.h
%{_includedir}/aws/dynamodb/model/ExportTableToPointInTimeResult.h
%{_includedir}/aws/dynamodb/model/FailureException.h
%{_includedir}/aws/dynamodb/model/Get.h
%{_includedir}/aws/dynamodb/model/GlobalSecondaryIndexAutoScalingUpdate.h
%{_includedir}/aws/dynamodb/model/ItemResponse.h
%{_includedir}/aws/dynamodb/model/KinesisDataStreamDestination.h
%{_includedir}/aws/dynamodb/model/ListContributorInsightsRequest.h
%{_includedir}/aws/dynamodb/model/ListContributorInsightsResult.h
%{_includedir}/aws/dynamodb/model/ListExportsRequest.h
%{_includedir}/aws/dynamodb/model/ListExportsResult.h
%{_includedir}/aws/dynamodb/model/ParameterizedStatement.h
%{_includedir}/aws/dynamodb/model/ProvisionedThroughputOverride.h
%{_includedir}/aws/dynamodb/model/Put.h
%{_includedir}/aws/dynamodb/model/ReplicaAutoScalingDescription.h
%{_includedir}/aws/dynamodb/model/ReplicaAutoScalingUpdate.h
%{_includedir}/aws/dynamodb/model/ReplicaGlobalSecondaryIndex.h
%{_includedir}/aws/dynamodb/model/ReplicaGlobalSecondaryIndexAutoScalingDescription.h
%{_includedir}/aws/dynamodb/model/ReplicaGlobalSecondaryIndexAutoScalingUpdate.h
%{_includedir}/aws/dynamodb/model/ReplicaGlobalSecondaryIndexDescription.h
%{_includedir}/aws/dynamodb/model/ReplicationGroupUpdate.h
%{_includedir}/aws/dynamodb/model/ReturnValuesOnConditionCheckFailure.h
%{_includedir}/aws/dynamodb/model/S3SseAlgorithm.h
%{_includedir}/aws/dynamodb/model/TableAutoScalingDescription.h
%{_includedir}/aws/dynamodb/model/TransactGetItem.h
%{_includedir}/aws/dynamodb/model/TransactGetItemsRequest.h
%{_includedir}/aws/dynamodb/model/TransactGetItemsResult.h
%{_includedir}/aws/dynamodb/model/TransactWriteItem.h
%{_includedir}/aws/dynamodb/model/TransactWriteItemsRequest.h
%{_includedir}/aws/dynamodb/model/TransactWriteItemsResult.h
%{_includedir}/aws/dynamodb/model/TransactionCanceledException.h
%{_includedir}/aws/dynamodb/model/Update.h
%{_includedir}/aws/dynamodb/model/UpdateContributorInsightsRequest.h
%{_includedir}/aws/dynamodb/model/UpdateContributorInsightsResult.h
%{_includedir}/aws/dynamodb/model/UpdateReplicationGroupMemberAction.h
%{_includedir}/aws/dynamodb/model/UpdateTableReplicaAutoScalingRequest.h
%{_includedir}/aws/dynamodb/model/UpdateTableReplicaAutoScalingResult.h
%{_includedir}/aws/event-stream/event_stream.h
%{_includedir}/aws/event-stream/event_stream_channel_handler.h
%{_includedir}/aws/event-stream/event_stream_exports.h
%{_includedir}/aws/event-stream/event_stream_rpc.h
%{_includedir}/aws/event-stream/event_stream_rpc_client.h
%{_includedir}/aws/event-stream/event_stream_rpc_server.h
%{_includedir}/aws/http/connection.h
%{_includedir}/aws/http/connection_manager.h
%{_includedir}/aws/http/exports.h
%{_includedir}/aws/http/http.h
%{_includedir}/aws/http/proxy.h
%{_includedir}/aws/http/request_response.h
%{_includedir}/aws/http/server.h
%{_includedir}/aws/http/statistics.h
%{_includedir}/aws/http/status_code.h
%{_includedir}/aws/http/websocket.h
%{_includedir}/aws/io/channel.h
%{_includedir}/aws/io/channel_bootstrap.h
%{_includedir}/aws/io/event_loop.h
%{_includedir}/aws/io/exports.h
%{_includedir}/aws/io/file_utils.h
%{_includedir}/aws/io/host_resolver.h
%{_includedir}/aws/io/io.h
%{_includedir}/aws/io/logging.h
%{_includedir}/aws/io/message_pool.h
%{_includedir}/aws/io/pipe.h
%{_includedir}/aws/io/retry_strategy.h
%{_includedir}/aws/io/shared_library.h
%{_includedir}/aws/io/socket.h
%{_includedir}/aws/io/socket_channel_handler.h
%{_includedir}/aws/io/statistics.h
%{_includedir}/aws/io/stream.h
%{_includedir}/aws/io/tls_channel_handler.h
%{_includedir}/aws/io/uri.h
%{_includedir}/aws/iot/MqttClient.h
%{_includedir}/aws/mqtt/client.h
%{_includedir}/aws/mqtt/exports.h
%{_includedir}/aws/mqtt/mqtt.h
%{_includedir}/aws/mqtt/private/mqtt_client_test_helper.h
%{_includedir}/aws/s3/exports.h
%{_includedir}/aws/s3/s3.h
%{_includedir}/aws/s3/s3_client.h
%{_includedir}/aws/testing/aws_test_allocators.h
%{_includedir}/aws/testing/aws_test_harness.h
%{_includedir}/aws/testing/io_testing_channel.h
%{_includedir}/aws/testing/mocks/aws/client/MockAWSClient.h
%{_includedir}/aws/testing/mocks/event/MockEventStreamDecoder.h
%{_includedir}/aws/testing/mocks/event/MockEventStreamHandler.h
%{_includedir}/aws/testing/mocks/monitoring/TestingMonitoring.h
%{_includedir}/s2n.h

%files dynamodb-libs
%{_libdir}/cmake/AWSSDK/AWSSDKConfig.cmake
%{_libdir}/cmake/AWSSDK/AWSSDKConfigVersion.cmake
%{_libdir}/cmake/AWSSDK/build_external.cmake
%{_libdir}/cmake/AWSSDK/compiler_settings.cmake
%{_libdir}/cmake/AWSSDK/dependencies.cmake
%{_libdir}/cmake/AWSSDK/external_dependencies.cmake
%{_libdir}/cmake/AWSSDK/initialize_project_version.cmake
%{_libdir}/cmake/AWSSDK/make_uninstall.cmake
%{_libdir}/cmake/AWSSDK/platform/android.cmake
%{_libdir}/cmake/AWSSDK/platform/apple.cmake
%{_libdir}/cmake/AWSSDK/platform/custom.cmake
%{_libdir}/cmake/AWSSDK/platform/linux.cmake
%{_libdir}/cmake/AWSSDK/platform/unix.cmake
%{_libdir}/cmake/AWSSDK/platform/windows.cmake
%{_libdir}/cmake/AWSSDK/platformDeps.cmake
%{_libdir}/cmake/AWSSDK/resolve_platform.cmake
%{_libdir}/cmake/AWSSDK/sdks.cmake
%{_libdir}/cmake/AWSSDK/sdksCommon.cmake
%{_libdir}/cmake/AWSSDK/setup_cmake_find_module.cmake
%{_libdir}/cmake/AWSSDK/utilities.cmake
%{_libdir}/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-config-version.cmake
%{_libdir}/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake
%{_libdir}/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-targets.cmake
%{_libdir}/cmake/aws-cpp-sdk-dynamodb/aws-cpp-sdk-dynamodb-config-version.cmake
%{_libdir}/cmake/aws-cpp-sdk-dynamodb/aws-cpp-sdk-dynamodb-config.cmake
%{_libdir}/cmake/aws-cpp-sdk-dynamodb/aws-cpp-sdk-dynamodb-targets.cmake
%{_libdir}/cmake/testing-resources/testing-resources-config-version.cmake
%{_libdir}/cmake/testing-resources/testing-resources-config.cmake
%{_libdir}/cmake/testing-resources/testing-resources-targets.cmake
%{_libdir}/libaws-cpp-sdk-core.a
%{_libdir}/libaws-cpp-sdk-dynamodb.a
%{_libdir}/libtesting-resources.a
%{_libdir}/cmake/AwsCFlags.cmake
%{_libdir}/cmake/AwsCheckHeaders.cmake
%{_libdir}/cmake/AwsFeatureTests.cmake
%{_libdir}/cmake/AwsFindPackage.cmake
%{_libdir}/cmake/AwsLibFuzzer.cmake
%{_libdir}/cmake/AwsSIMD.cmake
%{_libdir}/cmake/AwsSanitizers.cmake
%{_libdir}/cmake/AwsSharedLibSetup.cmake
%{_libdir}/cmake/AwsTestHarness.cmake
%{_libdir}/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-targets-release.cmake
%{_libdir}/cmake/aws-cpp-sdk-dynamodb/aws-cpp-sdk-dynamodb-targets-release.cmake
%{_libdir}/cmake/testing-resources/testing-resources-targets-release.cmake
%{_libdir}/libaws-c-auth.a
%{_libdir}/libaws-c-cal.a
%{_libdir}/libaws-c-common.a
%{_libdir}/libaws-c-compression.a
%{_libdir}/libaws-c-event-stream.a
%{_libdir}/libaws-c-http.a
%{_libdir}/libaws-c-io.a
%{_libdir}/libaws-c-mqtt.a
%{_libdir}/libaws-c-s3.a
%{_libdir}/libaws-checksums.a
%{_libdir}/libaws-crt-cpp.a
%{_libdir}/libs2n.a
%{_libdir}/aws-c-auth/cmake/aws-c-auth-config.cmake
%{_libdir}/aws-c-auth/cmake/static/aws-c-auth-targets-release.cmake
%{_libdir}/aws-c-auth/cmake/static/aws-c-auth-targets.cmake
%{_libdir}/aws-c-cal/cmake/aws-c-cal-config.cmake
%{_libdir}/aws-c-cal/cmake/modules/FindLibCrypto.cmake
%{_libdir}/aws-c-cal/cmake/static/aws-c-cal-targets-release.cmake
%{_libdir}/aws-c-cal/cmake/static/aws-c-cal-targets.cmake
%{_libdir}/aws-c-common/cmake/aws-c-common-config.cmake
%{_libdir}/aws-c-common/cmake/static/aws-c-common-targets-release.cmake
%{_libdir}/aws-c-common/cmake/static/aws-c-common-targets.cmake
%{_libdir}/aws-c-compression/cmake/aws-c-compression-config.cmake
%{_libdir}/aws-c-compression/cmake/static/aws-c-compression-targets-release.cmake
%{_libdir}/aws-c-compression/cmake/static/aws-c-compression-targets.cmake
%{_libdir}/aws-c-event-stream/cmake/aws-c-event-stream-config.cmake
%{_libdir}/aws-c-event-stream/cmake/static/aws-c-event-stream-targets-release.cmake
%{_libdir}/aws-c-event-stream/cmake/static/aws-c-event-stream-targets.cmake
%{_libdir}/aws-c-http/cmake/aws-c-http-config.cmake
%{_libdir}/aws-c-http/cmake/static/aws-c-http-targets-release.cmake
%{_libdir}/aws-c-http/cmake/static/aws-c-http-targets.cmake
%{_libdir}/aws-c-io/cmake/aws-c-io-config.cmake
%{_libdir}/aws-c-io/cmake/static/aws-c-io-targets-release.cmake
%{_libdir}/aws-c-io/cmake/static/aws-c-io-targets.cmake
%{_libdir}/aws-c-mqtt/cmake/aws-c-mqtt-config.cmake
%{_libdir}/aws-c-mqtt/cmake/static/aws-c-mqtt-targets-release.cmake
%{_libdir}/aws-c-mqtt/cmake/static/aws-c-mqtt-targets.cmake
%{_libdir}/aws-c-s3/cmake/aws-c-s3-config.cmake
%{_libdir}/aws-c-s3/cmake/static/aws-c-s3-targets-release.cmake
%{_libdir}/aws-c-s3/cmake/static/aws-c-s3-targets.cmake
%{_libdir}/aws-checksums/cmake/aws-checksums-config.cmake
%{_libdir}/aws-checksums/cmake/static/aws-checksums-targets-release.cmake
%{_libdir}/aws-checksums/cmake/static/aws-checksums-targets.cmake
%{_libdir}/aws-crt-cpp/cmake/aws-crt-cpp-config.cmake
%{_libdir}/aws-crt-cpp/cmake/static/aws-crt-cpp-targets-release.cmake
%{_libdir}/aws-crt-cpp/cmake/static/aws-crt-cpp-targets.cmake
%{_libdir}/s2n/cmake/modules/FindLibCrypto.cmake
%{_libdir}/s2n/cmake/s2n-config.cmake
%{_libdir}/s2n/cmake/static/s2n-targets-release.cmake
%{_libdir}/s2n/cmake/static/s2n-targets.cmake

%changelog
* Tue Nov 16 2021 Suchandra Thapa <sthapa@uchicago.edu> - 1.9.145-1
- Update to latest sdk

* Mon Aug 13 2018 Lincoln Bryant <lincolnb@uchicago.edu> - 1.4.70-1
- Initial package

